### PR TITLE
SKV client fix for dynamic schema use case

### LINKED ISSUE #41: Fix SKV client for dynamic schema usage
SKV client works for static schemas such as with TPC-C but does not work for the dynamic schema case of reading and writing SKVRecords. Fix it and add tests for it.

### PR DESCRIPTION
**Pull request by jfunston**
Fix for SKV dynamic schema use case plus simple test for it. Closes #41

### CODE REVIEW

File: src/k2/module/k23si/client/k23si_client.h [hunk 1]
```diff
@@ -99,7 +99,8 @@ k2::TSO_ClientLib& _tsoClient;
     seastar::future<Status> makeCollection(const String& collection, std::vector<k2::String>&& rangeEnds=std::vector<k2::String>());
     seastar::future<K2TxnHandle> beginTxn(const K2TxnOptions& options);
     static constexpr int64_t ANY_VERSION = -1;
-    seastar::future<Schema> getSchema(const String& collectionName, const String& schemaName, int64_t schemaVersion);
+    seastar::future<seastar::lw_shared_ptr<dto::Schema>> getSchema(const String& collectionName, const String& schemaName, int64_t schemaVersion, bool doCPORefresh=true);
+    seastar::future<Status> refreshSchemaCache(const String& collectionName);
```
Comment (iafuture) [inline src/k2/module/k23si/client/k23si_client.h:103]: It's a little confusing to have this as public. Am I supposed to use it as a user of the client lib?

File: src/k2/module/k23si/client/k23si_client.h [hunk 2]
```diff
@@ -99,7 +99,8 @@ k2::TSO_ClientLib& _tsoClient;
     seastar::future<Status> makeCollection(const String& collection, std::vector<k2::String>&& rangeEnds=std::vector<k2::String>());
     seastar::future<K2TxnHandle> beginTxn(const K2TxnOptions& options);
     static constexpr int64_t ANY_VERSION = -1;
-    seastar::future<Schema> getSchema(const String& collectionName, const String& schemaName, int64_t schemaVersion);
+    seastar::future<seastar::lw_shared_ptr<dto::Schema>> getSchema(const String& collectionName, const String& schemaName, int64_t schemaVersion, bool doCPORefresh=true);
```
Comment (iafuture) [inline src/k2/module/k23si/client/k23si_client.h:102]: Why is it up to the user to decide if they want to refresh? I think it should be an internal client lib decision to refresh as needed

File: src/k2/module/k23si/client/k23si_client.h [hunk 3]
```diff
@@ -174,7 +176,20 @@ class K2TxnHandle {
                 checkResponseStatus(status);
 
                 if constexpr (std::is_same<T, dto::SKVRecord>()) {
-                    return ReadResult<SKVRecord>(std::move(status), std::move(k2response.value));
+                    if (!status.is2xxOK()) {
+                        return seastar::make_ready_future<ReadResult<T>>(ReadResult<T>(std::move(status), SKVRecord()));
+                    }
+
+                    return _client->getSchema(request_cname, request_schema->name, k2response.value.schemaVersion)
+                    .then([s=std::move(status), storage=std::move(k2response.value), request_cname] (auto&& schema_ptr) mutable {
```
Comment (iafuture) [inline src/k2/module/k23si/client/k23si_client.h:184]: why copy request_cname here? also above on line #174, why capture request_cname by copy? Could we not capture by ref?

**Review by iafuture — CHANGES_REQUESTED** [review]

**Review by iafuture — APPROVED** [review]
